#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 22
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo ufw status
sudo systemctl start nginx
sudo systemctl enable nginx
