#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > /var/www/html

echo "Ceci n'est pas une page" > /var/www/html/404.html

SERVER_CONFIG=\
"server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}"


bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-available/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi

