#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get update
sudo apt-get install -y nginx 
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

SERVER_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    add_header X-Served-By \$hostname;
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}"


bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-available/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi


