#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 503786-web-01 18.207.142.82:80 check
   server 503786-web-02 54.162.43.2:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
